Repository kelompok-2-LastProject/ecommerce-2, pull requests merged in 2021-11, with the labels that each got.

#10 Vera
  package-lock.json
  src/modules/admin/products/pages/SalesRecap.page.jsx
  src/modules/admin/products/pages/UpdateProduct.page.jsx
  src/modules/shared/components/MyFooter.jsx
  src/modules/shared/components/MyNavbar.jsx
  src/modules/shared/redux/slices/products.js
  src/pages/admin/products/index.js
  src/pages/admin/sales/index.js
Labels: enhancement, hacktoberfest-accepted

#11 tri/feat/products
  src/modules/cart/pages/Cart.page.jsx
  src/modules/home/pages/Home.page.jsx
  src/modules/shared/components/MyPagination.jsx
  src/modules/shared/hooks/useMemoCompare.js
  src/modules/shared/hooks/usePagination.js
  src/modules/shared/redux/slices/cart.js
Labels: hacktoberfest-accepted

#12 v1.1
  .eslintignore
  .eslintrc
  .husky/pre-commit
  README.md
  next.config.js
  package-lock.json
  package.json
  pages/_app.js
  pages/api/hello.js
  pages/index.js
  public/favicon.ico
  public/logo-dark.png
  public/logo-light.png
  public/vercel.svg
  src/modules/admin/products/pages/SalesRecap.page.jsx
  src/modules/admin/products/pages/UpdateProduct.page.jsx
  src/modules/cart/pages/Cart.page.jsx
  src/modules/faq/mocks/index.js
  src/modules/faq/pages/FAQ.page.jsx
  src/modules/home/pages/Home.page.jsx
  src/modules/login/pages/Login.page.jsx
  src/modules/product/pages/ProductDetail.page.jsx
  src/modules/shared/components/Loader.jsx
  src/modules/shared/components/MyFooter.jsx
  src/modules/shared/components/MyNavbar.jsx
  src/modules/shared/components/MyPagination.jsx
  src/modules/shared/config/constants.js
  src/modules/shared/config/seo.js
  src/modules/shared/hooks/useDebounce.js
  src/modules/shared/hooks/useLocalStorage.js
  src/modules/shared/hooks/useMemoCompare.js
  src/modules/shared/hooks/usePagination.js
  src/modules/shared/redux/slices/cart.js
  src/modules/shared/redux/slices/checkout.js
  src/modules/shared/redux/slices/products.js
  src/modules/shared/redux/store.js
  src/modules/shared/services/products.js
  src/modules/shared/styles/globals.css
  src/modules/shared/utils/generateNumberFromInterval.js
  src/modules/shared/utils/truncateText.js
  src/modules/support/pages/Support.page.jsx
  src/pages/_app.js
  src/pages/_document.js
  src/pages/admin/products/index.js
  src/pages/admin/sales/index.js
  src/pages/cart/index.js
  src/pages/faq/index.js
  src/pages/index.js
  src/pages/login/index.js
  src/pages/products/[id]/index.js
  src/pages/support/index.js
  styles/Home.module.css
  styles/globals.css
Labels: enhancement, hacktoberfest-accepted

#13 feat: update products page
  src/modules/admin/products/pages/SalesRecap.page.jsx
  src/modules/admin/products/pages/UpdateProduct.page.jsx
  src/modules/shared/redux/slices/products.js
Labels: enhancement, hacktoberfest-accepted

#14 fix: add to cart
  README.md
  next.config.js
  src/modules/home/pages/Home.page.jsx
  src/modules/product/pages/ProductDetail.page.jsx
  src/modules/support/pages/Support.page.jsx
Labels: bug, enhancement, hacktoberfest-accepted

#16 v1.2
  README.md
  next.config.js
  public/banner1.jpg
  public/banner2.jpg
  public/banner3.jpg
  src/modules/admin/products/pages/SalesRecap.page.jsx
  src/modules/admin/products/pages/UpdateProduct.page.jsx
  src/modules/home/pages/Home.page.jsx
  src/modules/product/pages/ProductDetail.page.jsx
  src/modules/shared/components/MyNavbar.jsx
  src/modules/shared/redux/slices/products.js
  src/modules/support/pages/Support.page.jsx
Labels: bug, enhancement, hacktoberfest-accepted

#17 Vera
  src/modules/shared/components/Loader.jsx
Labels: good first issue, hacktoberfest-accepted

#18 change icon + add 404 page
  README.md
  public/favicon.ico
  public/female.png
  public/logo-dark.png
  public/logo-light.png
  src/modules/shared/components/MyFooter.jsx
  src/modules/shared/components/MyNavbar.jsx
  src/modules/shared/pages/Custom404.jsx
  src/pages/404.js
Labels: enhancement, hacktoberfest-accepted

#20 v1.2
  README.md
  public/favicon.ico
  public/female.png
  public/logo-dark.png
  public/logo-light.png
  src/modules/shared/components/Loader.jsx
  src/modules/shared/components/MyFooter.jsx
  src/modules/shared/components/MyNavbar.jsx
  src/modules/shared/pages/Custom404.jsx
  src/pages/404.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#21 Add more features
  package-lock.json
  package.json
  src/modules/admin/products/pages/SalesRecap.page.jsx
  src/modules/home/pages/Home.page.jsx
Labels: enhancement, hacktoberfest-accepted

#24 fix: html2pdf self is not defined
  README.md
  src/modules/admin/products/pages/SalesRecap.page.jsx
  src/pages/admin/sales/index.js
Labels: bug

#22 v1.3
  README.md
  package-lock.json
  package.json
  src/modules/admin/products/pages/SalesRecap.page.jsx
  src/modules/home/pages/Home.page.jsx
  src/pages/admin/sales/index.js
Labels: enhancement
